PROJECT = SecureVault.Console/SecureVault.Console.csproj

run:
	dotnet run --project $(PROJECT)

build:
	dotnet build $(PROJECT)

clean:
	dotnet clean $(PROJECT)

restore:
	dotnet restore $(PROJECT)

.PHONY: run build clean restore
